Упражнение 1:
После того как мы убрали unchecked, мы перестаем проверять на переполнение, тогда у нас сразу появится исключение OverflowException

Упражнение 2:
Посде того, как мы поменяли checked и unchecked местами, первый блок кода начнет выполняться с проверкой, но поскольку там есть умножение на ноль то переполнение никогда не возникнет, а второй блок выполняется без проверки, поэтому там выполнится обрезание до допустимого значения в случае переполнения

Упражнение 3:
В данном коде исключение DivideByZeroException не было сгенерировано потому, что деление на ноль возникает внутри блока try-конструкции, который обрабатывает это исключение. Когда происходит деление на ноль, программа переходит к обработчику исключений, который выводит сообщение "y({i})=Деление на 0" и продолжает выполнение цикла.

Упражнение4:

Входные данные:
a=4, b=2
Выходные данные:
4/2=2
После try-блока

Входные данные:
a=3, b=g
Выходные данные:
Нужно ввести число
После try-блока

Входные данные:
a=d, b=1
Выходные данные:
Нужно ввести число
После try-блока

Входные данные:
a=2, b=0,
Выходные данные:
Делить на ноль нельзя
После try-блока

Входные данные:
a=123456789987654321, b=1
Выходные данные:
Не обрабатывается исключение "Число слишком большое для типа Int32"
